<?php

return [
    ['name_en' => "Afghanistan", "name_ar" => "أفغانستان", "code" => "AF", "phone" => "93"],
    ['name_en' => "Aland Islands", "name_ar" => "جزر آلاند", "code" => "AX", "phone" => "358"],
    ['name_en' => "Albania", "name_ar" => "ألبانيا", "code" => "AL", "phone" => "355"],
    ['name_en' => "Algeria", "name_ar" => "الجزائر", "code" => "DZ", "phone" => "213"],
    ['name_en' => "American Samoa", "name_ar" => "ساموا الأمريكية", "code" => "AS", "phone" => "1684"],
    ['name_en' => "Andorra", "name_ar" => "أندورا", "code" => "AD", "phone" => "376"],
    ['name_en' => "Angola", "name_ar" => "أنغولا", "code" => "AO", "phone" => "244"],
    ['name_en' => "Anguilla", "name_ar" => "أنغيلا", "code" => "AI", "phone" => "1264"],
    ['name_en' => "Antarctica", "name_ar" => "أنتاركتيكا", "code" => "AQ", "phone" => "672"],
    ['name_en' => "Antigua and Barbuda", "name_ar" => "أنتيغوا وبربودا", "code" => "AG", "phone" => "1268"],
    ['name_en' => "Argentina", "name_ar" => "الأرجنتين", "code" => "AR", "phone" => "54"],
    ['name_en' => "Armenia", "name_ar" => "أرمينيا", "code" => "AM", "phone" => "374"],
    ['name_en' => "Aruba", "name_ar" => "أروبا", "code" => "AW", "phone" => "297"],
    ['name_en' => "Australia", "name_ar" => "أستراليا", "code" => "AU", "phone" => "61"],
    ['name_en' => "Austria", "name_ar" => "النمسا", "code" => "AT", "phone" => "43"],
    ['name_en' => "Azerbaijan", "name_ar" => "أذربيجان", "code" => "AZ", "phone" => "994"],
    ['name_en' => "Bahamas", "name_ar" => "جزر البهاما", "code" => "BS", "phone" => "1242"],
    ['name_en' => "Bahrain", "name_ar" => "البحرين", "code" => "BH", "phone" => "973"],
    ['name_en' => "Bangladesh", "name_ar" => "بنغلاديش", "code" => "BD", "phone" => "880"],
    ['name_en' => "Barbados", "name_ar" => "بربادوس", "code" => "BB", "phone" => "1246"],
    ['name_en' => "Belarus", "name_ar" => "بيلاروسيا", "code" => "BY", "phone" => "375"],
    ['name_en' => "Belgium", "name_ar" => "بلجيكا", "code" => "BE", "phone" => "32"],
    ['name_en' => "Belize", "name_ar" => "بليز", "code" => "BZ", "phone" => "501"],
    ['name_en' => "Benin", "name_ar" => "بنين", "code" => "BJ", "phone" => "229"],
    ['name_en' => "Bermuda", "name_ar" => "برمودا", "code" => "BM", "phone" => "1441"],
    ['name_en' => "Bhutan", "name_ar" => "بوتان", "code" => "BT", "phone" => "975"],
    ['name_en' => "Bolivia", "name_ar" => "بوليفيا", "code" => "BO", "phone" => "591"],
    ['name_en' => "Bonaire, Sint Eustatius and Saba", "name_ar" => "بونير وسانت يوستاتيوس وسابا", "code" => "BQ", "phone" => "599"],
    ['name_en' => "Bosnia and Herzegovina", "name_ar" => "البوسنة والهرسك", "code" => "BA", "phone" => "387"],
    ['name_en' => "Botswana", "name_ar" => "بوتسوانا", "code" => "BW", "phone" => "267"],
    ['name_en' => "Bouvet Island", "name_ar" => "جزيرة بوفيت", "code" => "BV", "phone" => "55"],
    ['name_en' => "Brazil", "name_ar" => "البرازيل", "code" => "BR", "phone" => "55"],
    ['name_en' => "British Indian Ocean Territory", "name_ar" => "إقليم المحيط البريطاني الهندي", "code" => "IO", "phone" => "246"],
    ['name_en' => "Brunei Darussalam", "name_ar" => "بروناي دار السلام", "code" => "BN", "phone" => "673"],
    ['name_en' => "Bulgaria", "name_ar" => "بلغاريا", "code" => "BG", "phone" => "359"],
    ['name_en' => "Burkina Faso", "name_ar" => "بوركينا فاسو", "code" => "BF", "phone" => "226"],
    ['name_en' => "Burundi", "name_ar" => "بوروندي", "code" => "BI", "phone" => "257"],
    ['name_en' => "Cambodia", "name_ar" => "كمبوديا", "code" => "KH", "phone" => "855"],
    ['name_en' => "Cameroon", "name_ar" => "الكاميرون", "code" => "CM", "phone" => "237"],
    ['name_en' => "Canada", "name_ar" => "كندا", "code" => "CA", "phone" => "1"],
    ['name_en' => "Cape Verde", "name_ar" => "الرأس الأخضر", "code" => "CV", "phone" => "238"],
    ['name_en' => "Cayman Islands", "name_ar" => "جزر كايمان", "code" => "KY", "phone" => "1345"],
    ['name_en' => "Central African Republic", "name_ar" => "جمهورية افريقيا الوسطى", "code" => "CF", "phone" => "236"],
    ['name_en' => "Chad", "name_ar" => "تشاد", "code" => "TD", "phone" => "235"],
    ['name_en' => "Chile", "name_ar" => "تشيلي", "code" => "CL", "phone" => "56"],
    ['name_en' => "China", "name_ar" => "الصين", "code" => "CN", "phone" => "86"],
    ['name_en' => "Christmas Island", "name_ar" => "جزيرة الكريسماس", "code" => "CX", "phone" => "61"],
    ['name_en' => "Cocos (Keeling) Islands", "name_ar" => "جزر كوكوس (كيلينغ)", "code" => "CC", "phone" => "672"],
    ['name_en' => "Colombia", "name_ar" => "كولومبيا", "code" => "CO", "phone" => "57"],
    ['name_en' => "Comoros", "name_ar" => "جزر القمر", "code" => "KM", "phone" => "269"],
    ['name_en' => "Congo", "name_ar" => "الكونغو", "code" => "CG", "phone" => "242"],
    ['name_en' => "Congo, Democratic Republic of the Congo", "name_ar" => "الكونغو ، جمهورية الكونغو الديمقراطية", "code" => "CD", "phone" => "242"],
    ['name_en' => "Cook Islands", "name_ar" => "جزر كوك", "code" => "CK", "phone" => "682"],
    ['name_en' => "Costa Rica", "name_ar" => "كوستا ريكا", "code" => "CR", "phone" => "506"],
    ['name_en' => "Cote D'Ivoire", "name_ar" => "ساحل العاج", "code" => "CI", "phone" => "225"],
    ['name_en' => "Croatia", "name_ar" => "كرواتيا", "code" => "HR", "phone" => "385"],
    ['name_en' => "Cuba", "name_ar" => "كوبا", "code" => "CU", "phone" => "53"],
    ['name_en' => "Curacao", "name_ar" => "كوراكاو", "code" => "CW", "phone" => "599"],
    ['name_en' => "Cyprus", "name_ar" => "قبرص", "code" => "CY", "phone" => "357"],
    ['name_en' => "Czech Republic", "name_ar" => "الجمهورية التشيكية", "code" => "CZ", "phone" => "420"],
    ['name_en' => "Denmark", "name_ar" => "الدنمارك", "code" => "DK", "phone" => "45"],
    ['name_en' => "Djibouti", "name_ar" => "جيبوتي", "code" => "DJ", "phone" => "253"],
    ['name_en' => "Dominica", "name_ar" => "دومينيكا", "code" => "DM", "phone" => "1767"],
    ['name_en' => "Dominican Republic", "name_ar" => "جمهورية الدومنيكان", "code" => "DO", "phone" => "1809"],
    ['name_en' => "Ecuador", "name_ar" => "الاكوادور", "code" => "EC", "phone" => "593"],
    ['name_en' => "Egypt", "name_ar" => "مصر", "code" => "EG", "phone" => "20"],
    ['name_en' => "El Salvador", "name_ar" => "السلفادور", "code" => "SV", "phone" => "503"],
    ['name_en' => "Equatorial Guinea", "name_ar" => "غينيا الإستوائية", "code" => "GQ", "phone" => "240"],
    ['name_en' => "Eritrea", "name_ar" => "إريتريا", "code" => "ER", "phone" => "291"],
    ['name_en' => "Estonia", "name_ar" => "إستونيا", "code" => "EE", "phone" => "372"],
    ['name_en' => "Ethiopia", "name_ar" => "أثيوبيا", "code" => "ET", "phone" => "251"],
    ['name_en' => "Falkland Islands (Malvinas)", "name_ar" => "جزر فوكلاند (مالفيناس)", "code" => "FK", "phone" => "500"],
    ['name_en' => "Faroe Islands", "name_ar" => "جزر فاروس", "code" => "FO", "phone" => "298"],
    ['name_en' => "Fiji", "name_ar" => "فيجي", "code" => "FJ", "phone" => "679"],
    ['name_en' => "Finland", "name_ar" => "فنلندا", "code" => "FI", "phone" => "358"],
    ['name_en' => "France", "name_ar" => "فرنسا", "code" => "FR", "phone" => "33"],
    ['name_en' => "French Guiana", "name_ar" => "غيانا الفرنسية", "code" => "GF", "phone" => "594"],
    ['name_en' => "French Polynesia", "name_ar" => "بولينيزيا الفرنسية", "code" => "PF", "phone" => "689"],
    ['name_en' => "French Southern Territories", "name_ar" => "المناطق الجنوبية لفرنسا", "code" => "TF", "phone" => "262"],
    ['name_en' => "Gabon", "name_ar" => "الجابون", "code" => "GA", "phone" => "241"],
    ['name_en' => "Gambia", "name_ar" => "غامبيا", "code" => "GM", "phone" => "220"],
    ['name_en' => "Georgia", "name_ar" => "جورجيا", "code" => "GE", "phone" => "995"],
    ['name_en' => "Germany", "name_ar" => "ألمانيا", "code" => "DE", "phone" => "49"],
    ['name_en' => "Ghana", "name_ar" => "غانا", "code" => "GH", "phone" => "233"],
    ['name_en' => "Gibraltar", "name_ar" => "جبل طارق", "code" => "GI", "phone" => "350"],
    ['name_en' => "Greece", "name_ar" => "اليونان", "code" => "GR", "phone" => "30"],
    ['name_en' => "Greenland", "name_ar" => "الأرض الخضراء", "code" => "GL", "phone" => "299"],
    ['name_en' => "Grenada", "name_ar" => "غرينادا", "code" => "GD", "phone" => "1473"],
    ['name_en' => "Guadeloupe", "name_ar" => "جوادلوب", "code" => "GP", "phone" => "590"],
    ['name_en' => "Guam", "name_ar" => "غوام", "code" => "GU", "phone" => "1671"],
    ['name_en' => "Guatemala", "name_ar" => "غواتيمالا", "code" => "GT", "phone" => "502"],
    ['name_en' => "Guernsey", "name_ar" => "غيرنسي", "code" => "GG", "phone" => "44"],
    ['name_en' => "Guinea", "name_ar" => "غينيا", "code" => "GN", "phone" => "224"],
    ['name_en' => "Guinea-Bissau", "name_ar" => "غينيا بيساو", "code" => "GW", "phone" => "245"],
    ['name_en' => "Guyana", "name_ar" => "غيانا", "code" => "GY", "phone" => "592"],
    ['name_en' => "Haiti", "name_ar" => "هايتي", "code" => "HT", "phone" => "509"],
    ['name_en' => "Heard Island and McDonald Islands", "name_ar" => "قلب الجزيرة وجزر ماكدونالز", "code" => "HM", "phone" => "0"],
    ['name_en' => "Holy See (Vatican City State)", "name_ar" => "الكرسي الرسولي (دولة الفاتيكان)", "code" => "VA", "phone" => "39"],
    ['name_en' => "Honduras", "name_ar" => "هندوراس", "code" => "HN", "phone" => "504"],
    ['name_en' => "Hong Kong", "name_ar" => "هونج كونج", "code" => "HK", "phone" => "852"],
    ['name_en' => "Hungary", "name_ar" => "هنغاريا", "code" => "HU", "phone" => "36"],
    ['name_en' => "Iceland", "name_ar" => "أيسلندا", "code" => "IS", "phone" => "354"],
    ['name_en' => "India", "name_ar" => "الهند", "code" => "IN", "phone" => "91"],
    ['name_en' => "Indonesia", "name_ar" => "إندونيسيا", "code" => "ID", "phone" => "62"],
    ['name_en' => "Iran, Islamic Republic of", "name_ar" => "جمهورية إيران الإسلامية", "code" => "IR", "phone" => "98"],
    ['name_en' => "Iraq", "name_ar" => "العراق", "code" => "IQ", "phone" => "964"],
    ['name_en' => "Ireland", "name_ar" => "أيرلندا", "code" => "IE", "phone" => "353"],
    ['name_en' => "Isle of Man", "name_ar" => "جزيرة آيل أوف مان", "code" => "IM", "phone" => "44"],
    ['name_en' => "Israel", "name_ar" => "إسرائيل", "code" => "IL", "phone" => "972"],
    ['name_en' => "Italy", "name_ar" => "إيطاليا", "code" => "IT", "phone" => "39"],
    ['name_en' => "Jamaica", "name_ar" => "جامايكا", "code" => "JM", "phone" => "1876"],
    ['name_en' => "Japan", "name_ar" => "اليابان", "code" => "JP", "phone" => "81"],
    ['name_en' => "Jersey", "name_ar" => "جيرسي", "code" => "JE", "phone" => "44"],
    ['name_en' => "Jordan", "name_ar" => "الأردن", "code" => "JO", "phone" => "962"],
    ['name_en' => "Kazakhstan", "name_ar" => "كازاخستان", "code" => "KZ", "phone" => "7"],
    ['name_en' => "Kenya", "name_ar" => "كينيا", "code" => "KE", "phone" => "254"],
    ['name_en' => "Kiribati", "name_ar" => "كيريباتي", "code" => "KI", "phone" => "686"],
    ['name_en' => "Korea, Democratic People's Republic of", "name_ar" => "كوريا، الجمهورية الشعبية الديمقراطية", "code" => "KP", "phone" => "850"],
    ['name_en' => "Korea, Republic of", "name_ar" => "جمهورية كوريا", "code" => "KR", "phone" => "82"],
    ['name_en' => "Kosovo", "name_ar" => "كوسوفو", "code" => "XK", "phone" => "381"],
    ['name_en' => "Kuwait", "name_ar" => "الكويت", "code" => "KW", "phone" => "965"],
    ['name_en' => "Kyrgyzstan", "name_ar" => "قيرغيزستان", "code" => "KG", "phone" => "996"],
    ['name_en' => "Lao People's Democratic Republic", "name_ar" => "جمهورية لاو الديمقراطية الشعبية", "code" => "LA", "phone" => "856"],
    ['name_en' => "Latvia", "name_ar" => "لاتفيا", "code" => "LV", "phone" => "371"],
    ['name_en' => "Lebanon", "name_ar" => "لبنان", "code" => "LB", "phone" => "961"],
    ['name_en' => "Lesotho", "name_ar" => "ليسوتو", "code" => "LS", "phone" => "266"],
    ['name_en' => "Liberia", "name_ar" => "ليبيريا", "code" => "LR", "phone" => "231"],
    ['name_en' => "Libyan Arab Jamahiriya", "name_ar" => "الجماهيرية العربية الليبية", "code" => "LY", "phone" => "218"],
    ['name_en' => "Liechtenstein", "name_ar" => "ليختنشتاين", "code" => "LI", "phone" => "423"],
    ['name_en' => "Lithuania", "name_ar" => "ليتوانيا", "code" => "LT", "phone" => "370"],
    ['name_en' => "Luxembourg", "name_ar" => "لوكسمبورغ", "code" => "LU", "phone" => "352"],
    ['name_en' => "Macao", "name_ar" => "ماكاو", "code" => "MO", "phone" => "853"],
    ['name_en' => "Macedonia, the Former Yugoslav Republic of", "name_ar" => "مقدونيا ، جمهورية يوغوسلافيا السابقة", "code" => "MK", "phone" => "389"],
    ['name_en' => "Madagascar", "name_ar" => "مدغشقر", "code" => "MG", "phone" => "261"],
    ['name_en' => "Malawi", "name_ar" => "ملاوي", "code" => "MW", "phone" => "265"],
    ['name_en' => "Malaysia", "name_ar" => "ماليزيا", "code" => "MY", "phone" => "60"],
    ['name_en' => "Maldives", "name_ar" => "جزر المالديف", "code" => "MV", "phone" => "960"],
    ['name_en' => "Mali", "name_ar" => "مالي", "code" => "ML", "phone" => "223"],
    ['name_en' => "Malta", "name_ar" => "مالطا", "code" => "MT", "phone" => "356"],
    ['name_en' => "Marshall Islands", "name_ar" => "جزر مارشال", "code" => "MH", "phone" => "692"],
    ['name_en' => "Martinique", "name_ar" => "مارتينيك", "code" => "MQ", "phone" => "596"],
    ['name_en' => "Mauritania", "name_ar" => "موريتانيا", "code" => "MR", "phone" => "222"],
    ['name_en' => "Mauritius", "name_ar" => "موريشيوس", "code" => "MU", "phone" => "230"],
    ['name_en' => "Mayotte", "name_ar" => "مايوت", "code" => "YT", "phone" => "269"],
    ['name_en' => "Mexico", "name_ar" => "المكسيك", "code" => "MX", "phone" => "52"],
    ['name_en' => "Micronesia, Federated States of", "name_ar" => "ولايات ميكرونيزيا الموحدة", "code" => "FM", "phone" => "691"],
    ['name_en' => "Moldova, Republic of", "name_ar" => "جمهورية مولدوفا", "code" => "MD", "phone" => "373"],
    ['name_en' => "Monaco", "name_ar" => "موناكو", "code" => "MC", "phone" => "377"],
    ['name_en' => "Mongolia", "name_ar" => "منغوليا", "code" => "MN", "phone" => "976"],
    ['name_en' => "Montenegro", "name_ar" => "الجبل الأسود", "code" => "ME", "phone" => "382"],
    ['name_en' => "Montserrat", "name_ar" => "مونتسيرات", "code" => "MS", "phone" => "1664"],
    ['name_en' => "Morocco", "name_ar" => "المغرب", "code" => "MA", "phone" => "212"],
    ['name_en' => "Mozambique", "name_ar" => "موزمبيق", "code" => "MZ", "phone" => "258"],
    ['name_en' => "Myanmar", "name_ar" => "ميانمار", "code" => "MM", "phone" => "95"],
    ['name_en' => "Namibia", "name_ar" => "ناميبيا", "code" => "NA", "phone" => "264"],
    ['name_en' => "Nauru", "name_ar" => "ناورو", "code" => "NR", "phone" => "674"],
    ['name_en' => "Nepal", "name_ar" => "نيبال", "code" => "NP", "phone" => "977"],
    ['name_en' => "Netherlands", "name_ar" => "هولندا", "code" => "NL", "phone" => "31"],
    ['name_en' => "Netherlands Antilles", "name_ar" => "جزر الأنتيل الهولندية", "code" => "AN", "phone" => "599"],
    ['name_en' => "New Caledonia", "name_ar" => "كاليدونيا الجديدة", "code" => "NC", "phone" => "687"],
    ['name_en' => "New Zealand", "name_ar" => "نيوزيلاندا", "code" => "NZ", "phone" => "64"],
    ['name_en' => "Nicaragua", "name_ar" => "نيكاراغوا", "code" => "NI", "phone" => "505"],
    ['name_en' => "Niger", "name_ar" => "النيجر", "code" => "NE", "phone" => "227"],
    ['name_en' => "Nigeria", "name_ar" => "نيجيريا", "code" => "NG", "phone" => "234"],
    ['name_en' => "Niue", "name_ar" => "نيوي", "code" => "NU", "phone" => "683"],
    ['name_en' => "Norfolk Island", "name_ar" => "جزيرة نورفولك", "code" => "NF", "phone" => "672"],
    ['name_en' => "Northern Mariana Islands", "name_ar" => "جزر مريانا الشمالية", "code" => "MP", "phone" => "1670"],
    ['name_en' => "Norway", "name_ar" => "النرويج", "code" => "NO", "phone" => "47"],
    ['name_en' => "Oman", "name_ar" => "سلطنة عمان", "code" => "OM", "phone" => "968"],
    ['name_en' => "Pakistan", "name_ar" => "باكستان", "code" => "PK", "phone" => "92"],
    ['name_en' => "Palau", "name_ar" => "بالاو", "code" => "PW", "phone" => "680"],
    ['name_en' => "Palestinian Territory, Occupied", "name_ar" => "الأراضي الفلسطينية المحتلة", "code" => "PS", "phone" => "970"],
    ['name_en' => "Panama", "name_ar" => "بنما", "code" => "PA", "phone" => "507"],
    ['name_en' => "Papua New Guinea", "name_ar" => "بابوا غينيا الجديدة", "code" => "PG", "phone" => "675"],
    ['name_en' => "Paraguay", "name_ar" => "باراغواي", "code" => "PY", "phone" => "595"],
    ['name_en' => "Peru", "name_ar" => "بيرو", "code" => "PE", "phone" => "51"],
    ['name_en' => "Philippines", "name_ar" => "فيلبيني", "code" => "PH", "phone" => "63"],
    ['name_en' => "Pitcairn", "name_ar" => "بيتكيرن", "code" => "PN", "phone" => "64"],
    ['name_en' => "Poland", "name_ar" => "بولندا", "code" => "PL", "phone" => "48"],
    ['name_en' => "Portugal", "name_ar" => "البرتغال", "code" => "PT", "phone" => "351"],
    ['name_en' => "Puerto Rico", "name_ar" => "بورتوريكو", "code" => "PR", "phone" => "1787"],
    ['name_en' => "Qatar", "name_ar" => "دولة قطر", "code" => "QA", "phone" => "974"],
    ['name_en' => "Reunion", "name_ar" => "جمع شمل", "code" => "RE", "phone" => "262"],
    ['name_en' => "Romania", "name_ar" => "رومانيا", "code" => "RO", "phone" => "40"],
    ['name_en' => "Russian Federation", "name_ar" => "الاتحاد الروسي", "code" => "RU", "phone" => "70"],
    ['name_en' => "Rwanda", "name_ar" => "رواندا", "code" => "RW", "phone" => "250"],
    ['name_en' => "Saint Barthelemy", "name_ar" => "سانت بارتيليمي", "code" => "BL", "phone" => "590"],
    ['name_en' => "Saint Helena", "name_ar" => "سانت هيلانة", "code" => "SH", "phone" => "290"],
    ['name_en' => "Saint Kitts and Nevis", "name_ar" => "سانت كيتس ونيفيس", "code" => "KN", "phone" => "1869"],
    ['name_en' => "Saint Lucia", "name_ar" => "القديسة لوسيا", "code" => "LC", "phone" => "1758"],
    ['name_en' => "Saint Martin", "name_ar" => "القديس مارتن", "code" => "MF", "phone" => "590"],
    ['name_en' => "Saint Pierre and Miquelon", "name_ar" => "سانت بيير وميكلون", "code" => "PM", "phone" => "508"],
    ['name_en' => "Saint Vincent and the Grenadines", "name_ar" => "سانت فنسنت وجزر غرينادين", "code" => "VC", "phone" => "1784"],
    ['name_en' => "Samoa", "name_ar" => "ساموا", "code" => "WS", "phone" => "684"],
    ['name_en' => "San Marino", "name_ar" => "سان مارينو", "code" => "SM", "phone" => "378"],
    ['name_en' => "Sao Tome and Principe", "name_ar" => "ساو تومي وبرينسيبي", "code" => "ST", "phone" => "239"],
    ['name_en' => "Saudi Arabia", "name_ar" => "المملكة العربية السعودية", "code" => "SA", "phone" => "966"],
    ['name_en' => "Senegal", "name_ar" => "السنغال", "code" => "SN", "phone" => "221"],
    ['name_en' => "Serbia", "name_ar" => "صربيا", "code" => "RS", "phone" => "381"],
    ['name_en' => "Serbia and Montenegro", "name_ar" => "صربيا والجبل الأسود", "code" => "CS", "phone" => "381"],
    ['name_en' => "Seychelles", "name_ar" => "سيشيل", "code" => "SC", "phone" => "248"],
    ['name_en' => "Sierra Leone", "name_ar" => "سيرا ليون", "code" => "SL", "phone" => "232"],
    ['name_en' => "Singapore", "name_ar" => "سنغافورة", "code" => "SG", "phone" => "65"],
    ['name_en' => "St Martin", "name_ar" => "سينت مارتن", "code" => "SX", "phone" => "1"],
    ['name_en' => "Slovakia", "name_ar" => "سلوفاكيا", "code" => "SK", "phone" => "421"],
    ['name_en' => "Slovenia", "name_ar" => "سلوفينيا", "code" => "SI", "phone" => "386"],
    ['name_en' => "Solomon Islands", "name_ar" => "جزر سليمان", "code" => "SB", "phone" => "677"],
    ['name_en' => "Somalia", "name_ar" => "الصومال", "code" => "SO", "phone" => "252"],
    ['name_en' => "South Africa", "name_ar" => "جنوب أفريقيا", "code" => "ZA", "phone" => "27"],
    ['name_en' => "South Georgia and the South Sandwich Islands", "name_ar" => "جورجيا الجنوبية وجزر ساندويتش الجنوبية", "code" => "GS", "phone" => "500"],
    ['name_en' => "South Sudan", "name_ar" => "جنوب السودان", "code" => "SS", "phone" => "211"],
    ['name_en' => "Spain", "name_ar" => "إسبانيا", "code" => "ES", "phone" => "34"],
    ['name_en' => "Sri Lanka", "name_ar" => "سيريلانكا", "code" => "LK", "phone" => "94"],
    ['name_en' => "Sudan", "name_ar" => "السودان", "code" => "SD", "phone" => "249"],
    ['name_en' => "Suriname", "name_ar" => "سورينام", "code" => "SR", "phone" => "597"],
    ['name_en' => "Svalbard and Jan Mayen", "name_ar" => "سفالبارد وجان ماين", "code" => "SJ", "phone" => "47"],
    ['name_en' => "Swaziland", "name_ar" => "سوازيلاند", "code" => "SZ", "phone" => "268"],
    ['name_en' => "Sweden", "name_ar" => "السويد", "code" => "SE", "phone" => "46"],
    ['name_en' => "Switzerland", "name_ar" => "سويسرا", "code" => "CH", "phone" => "41"],
    ['name_en' => "Syrian Arab Republic", "name_ar" => "الجمهورية العربية السورية", "code" => "SY", "phone" => "963"],
    ['name_en' => "Taiwan, Province of China", "name_ar" => "مقاطعة تايوان الصينية", "code" => "TW", "phone" => "886"],
    ['name_en' => "Tajikistan", "name_ar" => "طاجيكستان", "code" => "TJ", "phone" => "992"],
    ['name_en' => "Tanzania, United Republic of", "name_ar" => "جمهورية تنزانيا المتحدة", "code" => "TZ", "phone" => "255"],
    ['name_en' => "Thailand", "name_ar" => "تايلاند", "code" => "TH", "phone" => "66"],
    ['name_en' => "Timor-Leste", "name_ar" => "تيمور ليشتي", "code" => "TL", "phone" => "670"],
    ['name_en' => "Togo", "name_ar" => "توجو", "code" => "TG", "phone" => "228"],
    ['name_en' => "Tokelau", "name_ar" => "توكيلاو", "code" => "TK", "phone" => "690"],
    ['name_en' => "Tonga", "name_ar" => "تونغا", "code" => "TO", "phone" => "676"],
    ['name_en' => "Trinidad and Tobago", "name_ar" => "ترينداد وتوباغو", "code" => "TT", "phone" => "1868"],
    ['name_en' => "Tunisia", "name_ar" => "تونس", "code" => "TN", "phone" => "216"],
    ['name_en' => "Turkey", "name_ar" => "ديك رومى", "code" => "TR", "phone" => "90"],
    ['name_en' => "Turkmenistan", "name_ar" => "تركمانستان", "code" => "TM", "phone" => "7370"],
    ['name_en' => "Turks and Caicos Islands", "name_ar" => "جزر تركس وكايكوس", "code" => "TC", "phone" => "1649"],
    ['name_en' => "Tuvalu", "name_ar" => "توفالو", "code" => "TV", "phone" => "688"],
    ['name_en' => "Uganda", "name_ar" => "أوغندا", "code" => "UG", "phone" => "256"],
    ['name_en' => "Ukraine", "name_ar" => "أوكرانيا", "code" => "UA", "phone" => "380"],
    ['name_en' => "United Arab Emirates", "name_ar" => "الإمارات العربية المتحدة", "code" => "AE", "phone" => "971"],
    ['name_en' => "United Kingdom", "name_ar" => "المملكة المتحدة", "code" => "GB", "phone" => "44"],
    ['name_en' => "United States", "name_ar" => "الولايات المتحدة", "code" => "US", "phone" => "1"],
    ['name_en' => "United States Minor Outlying Islands", "name_ar" => "جزر الولايات المتحدة البعيدة الصغرى", "code" => "UM", "phone" => "1"],
    ['name_en' => "Uruguay", "name_ar" => "أوروغواي", "code" => "UY", "phone" => "598"],
    ['name_en' => "Uzbekistan", "name_ar" => "أوزبكستان", "code" => "UZ", "phone" => "998"],
    ['name_en' => "Vanuatu", "name_ar" => "فانواتو", "code" => "VU", "phone" => "678"],
    ['name_en' => "Venezuela", "name_ar" => "فنزويلا", "code" => "VE", "phone" => "58"],
    ['name_en' => "Viet Nam", "name_ar" => "فييت نام", "code" => "VN", "phone" => "84"],
    ['name_en' => "Virgin Islands, British", "name_ar" => "جزر العذراء البريطانية", "code" => "VG", "phone" => "1284"],
    ['name_en' => "Virgin Islands, U.s.", "name_ar" => "جزر فيرجن ، الولايات المتحدة", "code" => "VI", "phone" => "1340"],
    ['name_en' => "Wallis and Futuna", "name_ar" => "واليس وفوتونا", "code" => "WF", "phone" => "681"],
    ['name_en' => "Western Sahara", "name_ar" => "الصحراء الغربية", "code" => "EH", "phone" => "212"],
    ['name_en' => "Yemen", "name_ar" => "اليمن", "code" => "YE", "phone" => "967"],
    ['name_en' => "Zambia", "name_ar" => "زامبيا", "code" => "ZM", "phone" => "260"],
    ['name_en' => "Zimbabwe", "name_ar" => "زيمبابوي", "code" => "ZW", "phone" => "263"]
];
